name: indiabike
favicon: null
layout_spectrum: 0.5012
typography_spectrum: 0
title: Bringing Electricity and Transportation to India
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfaf6'
    - '#333436'
    - '#788490'
    - '#b2b2b4'
    - '#ed2931'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
