name: indiabike
favicon: null
layout_spectrum: 0.7543522643391043
typography_spectrum: 0.09669613838195801
title: Bringing Electricity and Transportation to India
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6174214610364288
  lightness: 0.04397480725310743
  saturation: 0.7789625078439713
  rhythmicContrast: 0.6821998942177743
purpose: []
