name: indiabike
favicon: null
layout_spectrum: 0.5012
typography_spectrum: 0
title: Bringing Electricity and Transportation to India
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfaf6'
    - '#333436'
    - '#788490'
    - '#b2b2b4'
    - '#ed2931'
  brandStrength: 0.6174214610364288
  lightness: 0.04397480725310743
  saturation: 0.7789625078439713
  rhythmicContrast: 0.6821998942177743
purpose: []
